# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.IntegerField(default=0)),
                ('nombre', models.CharField(max_length=125)),
                ('telefono', models.IntegerField(blank=True, default=0, null=True)),
                ('contacto', models.CharField(blank=True, max_length=125, null=True)),
                ('correo', models.EmailField(blank=True, max_length=125, null=True)),
                ('cargo', models.CharField(blank=True, max_length=125, null=True)),
            ],
        ),
    ]
