# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_auto_20170321_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nombre', models.CharField(max_length=125)),
            ],
        ),
    ]
