# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 18:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyecto', '0003_tipoproyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitCliente', models.IntegerField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('valor', models.IntegerField(default=0)),
                ('descripcion', models.CharField(max_length=125)),
                ('fechaEntregaDiseno', models.DateField()),
                ('fechaMuestraFisica', models.DateField()),
                ('fechaAprobacion', models.DateField()),
                ('fechaEntregaProduccion', models.DateField()),
                ('observacionFechas', models.CharField(max_length=125)),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nombreCliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.cliente')),
                ('tipoProyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.tipoProyecto')),
            ],
        ),
    ]
