# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 19:30
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='asesor',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
