# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0007_auto_20170323_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nitCliente',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
