# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 19:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0008_auto_20170323_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='fechaAprobacion',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='fechaEntregaDiseno',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='fechaEntregaProduccion',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='fechaMuestraFisica',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='observacionFechas',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='tipoProyecto',
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.CharField(default=django.utils.timezone.now, max_length=125),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2017, 3, 27, 19, 58, 1, 65475, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nitCliente',
            field=models.IntegerField(),
        ),
    ]
