# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0009_auto_20170327_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='descripcionP',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tipoProyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.tipoProyecto'),
        ),
    ]
