# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0010_auto_20170327_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='tipoProyecto',
            field=models.ForeignKey(blank=True, default='Tipo de proyecto', null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.tipoProyecto'),
        ),
    ]
