# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0013_auto_20170327_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='descripcionP',
            field=models.TextField(blank=True, max_length=125, null=True),
        ),
    ]
