# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 23:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0014_auto_20170327_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='prueba',
            field=models.CharField(default=django.utils.timezone.now, max_length=125),
            preserve_default=False,
        ),
    ]
