# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0015_cliente_prueba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='prueba',
        ),
    ]
