# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0017_auto_20170330_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='descripcionF',
            field=models.TextField(blank=True, max_length=125, null=True),
        ),
    ]
