# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0018_proyecto_descripcionf'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='prueba',
            field=models.CharField(choices=[('FR', 'Freshman'), ('b', 'b')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
