# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0019_proyecto_prueba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='prueba',
            field=models.CharField(blank=True, choices=[('FR', 'Freshman'), ('b', 'b')], max_length=10, null=True),
        ),
    ]
