# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0021_remove_proyecto_prueba'),
    ]

    operations = [
        migrations.CreateModel(
            name='opcionesD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
            ],
        ),
    ]
