# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0026_imgpyc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgpyc',
            name='proyecto',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
