# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diseno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='detalleProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presupuesto', models.CharField(blank=True, max_length=10, null=True)),
                ('unidades', models.CharField(blank=True, max_length=10, null=True)),
                ('total', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='idProyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyecto'),
        ),
        migrations.AddField(
            model_name='detalleproducto',
            name='idProducto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diseno.producto'),
        ),
    ]
