# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseno', '0002_auto_20170403_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
