# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseno', '0005_auto_20170410_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='muestraF',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='numeroP',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
