# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseno', '0009_auto_20170410_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='acabadosGalvanico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='acabados',
            field=models.ManyToManyField(blank=True, to='diseno.acabadosGalvanico'),
        ),
    ]
