# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseno', '0010_auto_20170410_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcionP',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='empaque',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='insumosD',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
