# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseno', '0011_auto_20170411_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='disenadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
    ]
