# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diseno', '0012_disenadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='disenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diseno.disenadores'),
        ),
    ]
